# Generated by Django 5.2.3 on 2025-09-29 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='session_type',
            field=models.CharField(choices=[('product', 'Product Shoot'), ('portrait', 'Portrait Session'), ('corporate', 'Corporate Photo Session')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
