# Generated by Django 5.2.3 on 2025-09-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='session_type',
            field=models.CharField(choices=[('jewelry', 'Jewelry Photography'), ('portrait', 'Portrait Photography'), ('wedding', 'Wedding Photography'), ('birthday', 'Birthday Photography'), ('pre_wedding', 'Pre-Wedding Shoots'), ('clothing_fashion', 'Clothing & Fashion Photography'), ('automobile', 'Auto-Mobile Photography'), ('business_professional', 'Business & Professional')], max_length=30),
        ),
    ]
